language: node_js
node_js:
  - 6
addons:
  chrome: stable
before_install:
  - #"export DISPLAY=:99.0"
  - #"sh -e /etc/init.d/xvfb start"
  - #start your web application and listen on `localhost`
  - #google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox http://localhost &
